// This file is a manual replica of the types generated by Prisma.
// It's used to decouple the application from the Prisma generation step,
// which is useful for Docker builds where the database may not be available.

// --- Enums ---

export enum ProcessType {
	MAINTENANCE = 'MAINTENANCE',
	FINANCIAL = 'FINANCIAL',
	SUPPLY = 'SUPPLY',
}

export enum ProcessStatus {
	ACTIVE = 'ACTIVE',
	COMPLETED = 'COMPLETED',
	OVERDUE = 'OVERDUE',
	AT_RISK = 'AT_RISK',
}

export enum StageKey {
	R = 'R',
	I = 'I',
	D = 'D',
	E = 'E',
	C = 'C',
}

export enum MaintenanceType {
	PREVENTIVE = 'PREVENTIVE',
	CORRECTIVE = 'CORRECTIVE',
	EMERGENCY = 'EMERGENCY',
}

export enum AIInsightType {
	PREDICTION = 'PREDICTION',
	ANOMALY = 'ANOMALY',
	RECOMMENDATION = 'RECOMMENDATION',
}

// --- Entities / Models ---

export interface Alerts {
	id: string;
	processId: string;
	alertMessage: string;
	alertLevel: number;
	createdAt: Date;
	updatedAt: Date;
	process?: Process;
}

export interface ProcessStage {
	id: string;
	processId: string;
	stageKey: StageKey;
	startTime: Date | null;
	endTime: Date | null;
	sla: number;
	createdAt: Date;
	updatedAt: Date;
	process?: Process;
}

export interface ProcessEvent {
	id: string;
	processId: string;
	event: string;
	data: any; // Prisma's Json type
	timestamp: Date;
	process?: Process;
}

export interface AIInsight {
	id: string;
	processId: string;
	type: AIInsightType;
	confidence: number;
	message: string;
	timestamp: Date;
	process?: Process;
}

export interface Process {
	id: string;
	title: string;
	type: ProcessType;
	vehicleId: string | null;
	currentStage: StageKey;
	status: ProcessStatus;
	createdAt: Date;
	updatedAt: Date;
	predictedCompletionTime: Date | null;
	riskScore: number | null;
	stages?: ProcessStage[];
	events?: ProcessEvent[];
	aiInsights?: AIInsight[];
	alerts?: Alerts[];
}
